#!/usr/bin/env python3
"""Build knowledge/08-example-patterns/INDEX.md from the actual card files.

Characterise-first: the index is generated from disk, so it is always complete and
in sync. Re-run after adding cards. Reads each card's `# Pattern card — TITLE`,
`- **Paradigm:**`, and `- **Problem it solves:**` lines.

Usage (from the project root  ie-simulation-copilot/):
    python scripts/build-pattern-index.py
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
PATTERNS = ROOT / "knowledge" / "08-example-patterns"
SUBFOLDERS = ["basicmodels", "models", "sdmodels"]
SKIP = {"README.md"}

TITLE_RE = re.compile(r"^#\s*Pattern card\s*[—\-:]\s*(.+?)\s*$", re.M)
PARADIGM_RE = re.compile(r"-\s*\*\*Paradigm:\*\*\s*(.+?)\s*$", re.M)
PROBLEM_RE = re.compile(r"-\s*\*\*Problem it solves:\*\*\s*(.+?)\s*$", re.M)


def card_fields(md: str):
    title = TITLE_RE.search(md)
    paradigm = PARADIGM_RE.search(md)
    problem = PROBLEM_RE.search(md)
    return (
        title.group(1).strip() if title else None,
        paradigm.group(1).strip() if paradigm else "?",
        problem.group(1).strip() if problem else "",
    )


def truncate(text: str, n: int = 130) -> str:
    text = text.replace("|", "\\|")
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def main() -> int:
    if not PATTERNS.is_dir():
        print(f"ERROR: {PATTERNS} not found", file=sys.stderr)
        return 1

    out = [
        "# 08-example-patterns — INDEX",
        "",
        "> AUTO-GENERATED by `scripts/build-pattern-index.py`. Do not edit by hand;",
        "> re-run the script after adding or changing cards.",
        "",
        "**__COUNT__ cards indexed.**",
        "",
        "Routing surface over the distilled AnyLogic pattern cards. Find a card by",
        "**paradigm** (DES / ABM / SD / hybrid) and **problem**, then open it for the",
        "block chain, settings, and KPIs.",
        "",
        "**Folder meaning:** `basicmodels/` = AnyLogic *How-to / basic* examples, often",
        "split into incremental `-phase-N` builds. `models/` = full *industry* example",
        "models. `sdmodels/` = System Dynamics library models. The same topic (e.g.",
        "job-shop, bass-diffusion) may appear in more than one folder at different depth.",
        "",
    ]

    total = 0
    missing = []
    for sub in SUBFOLDERS:
        d = PATTERNS / sub
        if not d.is_dir():
            continue
        cards = sorted(p for p in d.glob("*.md") if p.name not in SKIP)
        out.append(f"## {sub}/  ({len(cards)} cards)")
        out.append("")
        out.append("| Card | Paradigm | Problem it solves |")
        out.append("|---|---|---|")
        for p in cards:
            title, paradigm, problem = card_fields(p.read_text(encoding="utf-8"))
            if title is None or not problem:
                missing.append(str(p.relative_to(ROOT)))
            link = f"[{title or p.stem}]({sub}/{p.name})"
            out.append(f"| {link} | {paradigm} | {truncate(problem)} |")
            total += 1
        out.append("")

    text = "\n".join(out).replace("__COUNT__", str(total)) + "\n"
    (PATTERNS / "INDEX.md").write_text(text, encoding="utf-8")
    print(f"Wrote {PATTERNS / 'INDEX.md'} — {total} cards.")
    if missing:
        print(f"WARNING: {len(missing)} card(s) missing title/problem field:")
        for m in missing:
            print(f"  - {m}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
